export const BackendRenderTarget_MakeDirect3D = () => {}
export const org_jetbrains_skia_BackendRenderTarget__1nMakeGL = () => {}
export const BackendRenderTarget_nMakeMetal = () => {}
export const org_jetbrains_skia_BackendRenderTarget__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Bitmap__1nAllocPixels = () => {}
export const org_jetbrains_skia_Bitmap__1nAllocPixelsFlags = () => {}
export const org_jetbrains_skia_Bitmap__1nAllocPixelsRowBytes = () => {}
export const org_jetbrains_skia_Bitmap__1nComputeByteSize = () => {}
export const org_jetbrains_skia_Bitmap__1nComputeIsOpaque = () => {}
export const org_jetbrains_skia_Bitmap__1nErase = () => {}
export const org_jetbrains_skia_Bitmap__1nEraseColor = () => {}
export const org_jetbrains_skia_Bitmap__1nExtractAlpha = () => {}
export const org_jetbrains_skia_Bitmap__1nExtractSubset = () => {}
export const org_jetbrains_skia_Bitmap__1nGetAlphaf = () => {}
export const org_jetbrains_skia_Bitmap__1nGetGenerationId = () => {}
export const org_jetbrains_skia_Bitmap__1nGetImageInfo = () => {}
export const org_jetbrains_skia_Bitmap__1nGetPixelRef = () => {}
export const org_jetbrains_skia_Bitmap__1nGetPixelRefOriginX = () => {}
export const org_jetbrains_skia_Bitmap__1nGetPixelRefOriginY = () => {}
export const org_jetbrains_skia_Bitmap__1nGetPixmap = () => {}
export const org_jetbrains_skia_Bitmap__1nGetRowBytes = () => {}
export const org_jetbrains_skia_Bitmap__1nGetRowBytesAsPixels = () => {}
export const org_jetbrains_skia_Bitmap__1nInstallPixels = () => {}
export const org_jetbrains_skia_Bitmap__1nIsImmutable = () => {}
export const org_jetbrains_skia_Bitmap__1nIsNull = () => {}
export const org_jetbrains_skia_Bitmap__1nIsReadyToDraw = () => {}
export const org_jetbrains_skia_Bitmap__1nIsVolatile = () => {}
export const org_jetbrains_skia_Bitmap__1nMake = () => {}
export const org_jetbrains_skia_Bitmap__1nMakeClone = () => {}
export const org_jetbrains_skia_Bitmap__1nMakeShader = () => {}
export const org_jetbrains_skia_Bitmap__1nNotifyPixelsChanged = () => {}
export const org_jetbrains_skia_Bitmap__1nPeekPixels = () => {}
export const org_jetbrains_skia_Bitmap__1nReadPixels = () => {}
export const org_jetbrains_skia_Bitmap__1nReset = () => {}
export const org_jetbrains_skia_Bitmap__1nSetAlphaType = () => {}
export const org_jetbrains_skia_Bitmap__1nSetImageInfo = () => {}
export const org_jetbrains_skia_Bitmap__1nSetImmutable = () => {}
export const org_jetbrains_skia_Bitmap__1nSetPixelRef = () => {}
export const org_jetbrains_skia_Bitmap__1nSetVolatile = () => {}
export const org_jetbrains_skia_Bitmap__1nSwap = () => {}
export const org_jetbrains_skia_Bitmap__1nGetColor = () => {}
export const org_jetbrains_skia_Bitmap__1nGetFinalizer = () => {}
export const org_jetbrains_skia_BreakIterator__1nClone = () => {}
export const org_jetbrains_skia_BreakIterator__1nCurrent = () => {}
export const org_jetbrains_skia_BreakIterator__1nFirst = () => {}
export const org_jetbrains_skia_BreakIterator__1nFollowing = () => {}
export const org_jetbrains_skia_BreakIterator__1nGetRuleStatus = () => {}
export const org_jetbrains_skia_BreakIterator__1nGetRuleStatuses = () => {}
export const org_jetbrains_skia_BreakIterator__1nGetRuleStatusesLen = () => {}
export const org_jetbrains_skia_BreakIterator__1nIsBoundary = () => {}
export const org_jetbrains_skia_BreakIterator__1nLast = () => {}
export const org_jetbrains_skia_BreakIterator__1nMake = () => {}
export const org_jetbrains_skia_BreakIterator__1nNext = () => {}
export const org_jetbrains_skia_BreakIterator__1nPreceding = () => {}
export const org_jetbrains_skia_BreakIterator__1nPrevious = () => {}
export const org_jetbrains_skia_BreakIterator__1nSetText = () => {}
export const org_jetbrains_skia_BreakIterator__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Canvas__1nClear = () => {}
export const org_jetbrains_skia_Canvas__1nClipPath = () => {}
export const org_jetbrains_skia_Canvas__1nClipRect = () => {}
export const org_jetbrains_skia_Canvas__1nClipRegion = () => {}
export const org_jetbrains_skia_Canvas__1nClipRRect = () => {}
export const org_jetbrains_skia_Canvas__1nConcat = () => {}
export const org_jetbrains_skia_Canvas__1nConcat44 = () => {}
export const org_jetbrains_skia_Canvas__1nDrawArc = () => {}
export const org_jetbrains_skia_Canvas__1nDrawDrawable = () => {}
export const org_jetbrains_skia_Canvas__1nDrawDRRect = () => {}
export const org_jetbrains_skia_Canvas__1nDrawImageNine = () => {}
export const org_jetbrains_skia_Canvas__1nDrawImageRect = () => {}
export const org_jetbrains_skia_Canvas__1nDrawLine = () => {}
export const org_jetbrains_skia_Canvas__1nDrawOval = () => {}
export const org_jetbrains_skia_Canvas__1nDrawPaint = () => {}
export const org_jetbrains_skia_Canvas__1nDrawPatch = () => {}
export const org_jetbrains_skia_Canvas__1nDrawPath = () => {}
export const org_jetbrains_skia_Canvas__1nDrawPicture = () => {}
export const org_jetbrains_skia_Canvas__1nDrawPoint = () => {}
export const org_jetbrains_skia_Canvas__1nDrawPoints = () => {}
export const org_jetbrains_skia_Canvas__1nDrawRect = () => {}
export const org_jetbrains_skia_Canvas__1nDrawRegion = () => {}
export const org_jetbrains_skia_Canvas__1nDrawRRect = () => {}
export const org_jetbrains_skia_Canvas__1nDrawString = () => {}
export const org_jetbrains_skia_Canvas__1nDrawTextBlob = () => {}
export const org_jetbrains_skia_Canvas__1nDrawVertices = () => {}
export const org_jetbrains_skia_Canvas__1nGetLocalToDevice = () => {}
export const org_jetbrains_skia_Canvas__1nGetSaveCount = () => {}
export const org_jetbrains_skia_Canvas__1nMakeFromBitmap = () => {}
export const org_jetbrains_skia_Canvas__1nReadPixels = () => {}
export const org_jetbrains_skia_Canvas__1nResetMatrix = () => {}
export const org_jetbrains_skia_Canvas__1nRestore = () => {}
export const org_jetbrains_skia_Canvas__1nRestoreToCount = () => {}
export const org_jetbrains_skia_Canvas__1nRotate = () => {}
export const org_jetbrains_skia_Canvas__1nSave = () => {}
export const org_jetbrains_skia_Canvas__1nSaveLayer = () => {}
export const org_jetbrains_skia_Canvas__1nSaveLayerRect = () => {}
export const org_jetbrains_skia_Canvas__1nScale = () => {}
export const org_jetbrains_skia_Canvas__1nSetMatrix = () => {}
export const org_jetbrains_skia_Canvas__1nSkew = () => {}
export const org_jetbrains_skia_Canvas__1nTranslate = () => {}
export const org_jetbrains_skia_Canvas__1nWritePixels = () => {}
export const org_jetbrains_skia_Canvas__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Codec__1nGetEncodedImageFormat = () => {}
export const org_jetbrains_skia_Codec__1nGetEncodedOrigin = () => {}
export const org_jetbrains_skia_Codec__1nGetFrameCount = () => {}
export const org_jetbrains_skia_Codec__1nGetFrameInfo = () => {}
export const org_jetbrains_skia_Codec__1nGetFramesInfo = () => {}
export const org_jetbrains_skia_Codec__1nGetRepetitionCount = () => {}
export const org_jetbrains_skia_Codec__1nGetSizeHeight = () => {}
export const org_jetbrains_skia_Codec__1nGetSizeWidth = () => {}
export const org_jetbrains_skia_Codec__1nMakeFromData = () => {}
export const org_jetbrains_skia_Codec__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Codec__1nGetImageInfo = () => {}
export const org_jetbrains_skia_Codec__1nReadPixels = () => {}
export const org_jetbrains_skia_Codec__1nFramesInfo_Delete = () => {}
export const org_jetbrains_skia_Codec__1nFramesInfo_GetInfos = () => {}
export const org_jetbrains_skia_Codec__1nFramesInfo_GetSize = () => {}
export const org_jetbrains_skia_ColorFilter__1nGetLinearToSRGBGamma = () => {}
export const org_jetbrains_skia_ColorFilter__1nGetLuma = () => {}
export const org_jetbrains_skia_ColorFilter__1nGetSRGBToLinearGamma = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeBlend = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeComposed = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeHighContrast = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeHSLAMatrix = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeLerp = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeLighting = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeMatrix = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeOverdraw = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeTable = () => {}
export const org_jetbrains_skia_ColorFilter__1nMakeTableARGB = () => {}
export const org_jetbrains_skia_ColorSpace__nConvert = () => {}
export const org_jetbrains_skia_ColorSpace__1nIsGammaCloseToSRGB = () => {}
export const org_jetbrains_skia_ColorSpace__1nIsGammaLinear = () => {}
export const org_jetbrains_skia_ColorSpace__1nIsSRGB = () => {}
export const org_jetbrains_skia_ColorSpace__1nMakeDisplayP3 = () => {}
export const org_jetbrains_skia_ColorSpace__1nMakeSRGB = () => {}
export const org_jetbrains_skia_ColorSpace__1nMakeSRGBLinear = () => {}
export const org_jetbrains_skia_ColorSpace__1nGetFinalizer = () => {}
export const org_jetbrains_skia_ColorType__1nIsAlwaysOpaque = () => {}
export const org_jetbrains_skia_Data__1nBytes = () => {}
export const org_jetbrains_skia_Data__1nEquals = () => {}
export const org_jetbrains_skia_Data__1nMakeEmpty = () => {}
export const org_jetbrains_skia_Data__1nMakeFromBytes = () => {}
export const org_jetbrains_skia_Data__1nMakeFromFileName = () => {}
export const org_jetbrains_skia_Data__1nMakeSubset = () => {}
export const org_jetbrains_skia_Data__1nMakeUninitialized = () => {}
export const org_jetbrains_skia_Data__1nMakeWithoutCopy = () => {}
export const org_jetbrains_skia_Data__1nSize = () => {}
export const org_jetbrains_skia_Data__1nWritableData = () => {}
export const org_jetbrains_skia_Data__1nGetFinalizer = () => {}
export const org_jetbrains_skia_DirectContext__1nAbandon = () => {}
export const org_jetbrains_skia_DirectContext__1nMakeDirect3D = () => {}
export const org_jetbrains_skia_DirectContext__1nMakeGL = () => {}
export const org_jetbrains_skia_DirectContext__1nMakeMetal = () => {}
export const org_jetbrains_skia_DirectContext__1nReset = () => {}
export const org_jetbrains_skia_DirectContext__1nSubmit = () => {}
export const org_jetbrains_skia_DirectContext__1nFlush = () => {}
export const org_jetbrains_skia_Drawable__1nDraw = () => {}
export const org_jetbrains_skia_Drawable__1nGetOnDrawCanvas = () => {}
export const org_jetbrains_skia_Drawable__1nMakePictureSnapshot = () => {}
export const org_jetbrains_skia_Drawable__1nNotifyDrawingChanged = () => {}
export const org_jetbrains_skia_Drawable__1nSetBounds = () => {}
export const org_jetbrains_skia_Drawable__1nGetBounds = () => {}
export const org_jetbrains_skia_Drawable__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Drawable__1nGetGenerationId = () => {}
export const org_jetbrains_skia_Drawable__1nInit = () => {}
export const org_jetbrains_skia_Drawable__1nMake = () => {}
export const org_jetbrains_skia_Font__1nAreBitmapsEmbedded = () => {}
export const org_jetbrains_skia_Font__1nAreMetricsLinear = () => {}
export const org_jetbrains_skia_Font__1nGetBounds = () => {}
export const org_jetbrains_skia_Font__1nGetEdging = () => {}
export const org_jetbrains_skia_Font__1nGetHinting = () => {}
export const org_jetbrains_skia_Font__1nGetMetrics = () => {}
export const org_jetbrains_skia_Font__1nGetPath = () => {}
export const org_jetbrains_skia_Font__1nGetPaths = () => {}
export const org_jetbrains_skia_Font__1nGetPositions = () => {}
export const org_jetbrains_skia_Font__1nGetScaleX = () => {}
export const org_jetbrains_skia_Font__1nGetSkewX = () => {}
export const org_jetbrains_skia_Font__1nGetSpacing = () => {}
export const org_jetbrains_skia_Font__1nGetStringGlyphsCount = () => {}
export const org_jetbrains_skia_Font__1nGetTypeface = () => {}
export const org_jetbrains_skia_Font__1nGetTypefaceOrDefault = () => {}
export const org_jetbrains_skia_Font__1nGetUTF32Glyph = () => {}
export const org_jetbrains_skia_Font__1nGetUTF32Glyphs = () => {}
export const org_jetbrains_skia_Font__1nGetWidths = () => {}
export const org_jetbrains_skia_Font__1nGetXPositions = () => {}
export const org_jetbrains_skia_Font__1nIsAutoHintingForced = () => {}
export const org_jetbrains_skia_Font__1nIsBaselineSnapped = () => {}
export const org_jetbrains_skia_Font__1nIsEmboldened = () => {}
export const org_jetbrains_skia_Font__1nIsSubpixel = () => {}
export const org_jetbrains_skia_Font__1nMakeDefault = () => {}
export const org_jetbrains_skia_Font__1nMakeTypeface = () => {}
export const org_jetbrains_skia_Font__1nMakeTypefaceSize = () => {}
export const org_jetbrains_skia_Font__1nMakeTypefaceSizeScaleSkew = () => {}
export const org_jetbrains_skia_Font__1nMeasureText = () => {}
export const org_jetbrains_skia_Font__1nMeasureTextWidth = () => {}
export const org_jetbrains_skia_Font__1nSetAutoHintingForced = () => {}
export const org_jetbrains_skia_Font__1nSetBaselineSnapped = () => {}
export const org_jetbrains_skia_Font__1nSetBitmapsEmbedded = () => {}
export const org_jetbrains_skia_Font__1nSetEdging = () => {}
export const org_jetbrains_skia_Font__1nSetEmboldened = () => {}
export const org_jetbrains_skia_Font__1nSetHinting = () => {}
export const org_jetbrains_skia_Font__1nSetMetricsLinear = () => {}
export const org_jetbrains_skia_Font__1nSetScaleX = () => {}
export const org_jetbrains_skia_Font__1nSetSize = () => {}
export const org_jetbrains_skia_Font__1nSetSkewX = () => {}
export const org_jetbrains_skia_Font__1nSetSubpixel = () => {}
export const org_jetbrains_skia_Font__1nSetTypeface = () => {}
export const org_jetbrains_skia_Font__1nEquals = () => {}
export const org_jetbrains_skia_Font__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Font__1nGetSize = () => {}
export const org_jetbrains_skia_Font__1nMakeClone = () => {}
export const org_jetbrains_skia_FontMgr__1nDefault = () => {}
export const org_jetbrains_skia_FontMgr__1nGetFamiliesCount = () => {}
export const org_jetbrains_skia_FontMgr__1nGetFamilyName = () => {}
export const org_jetbrains_skia_FontMgr__1nMakeFromData = () => {}
export const org_jetbrains_skia_FontMgr__1nMakeStyleSet = () => {}
export const org_jetbrains_skia_FontMgr__1nMatchFamily = () => {}
export const org_jetbrains_skia_FontMgr__1nMatchFamilyStyle = () => {}
export const org_jetbrains_skia_FontMgr__1nMatchFamilyStyleCharacter = () => {}
export const org_jetbrains_skia_FontStyleSet__1nCount = () => {}
export const org_jetbrains_skia_FontStyleSet__1nGetStyle = () => {}
export const org_jetbrains_skia_FontStyleSet__1nGetStyleName = () => {}
export const org_jetbrains_skia_FontStyleSet__1nGetTypeface = () => {}
export const org_jetbrains_skia_FontStyleSet__1nMatchStyle = () => {}
export const org_jetbrains_skia_FontStyleSet__1nMakeEmpty = () => {}
export const org_jetbrains_skia_GraphicsKt__1nGetFontCacheCountLimit = () => {}
export const org_jetbrains_skia_GraphicsKt__1nGetFontCacheCountUsed = () => {}
export const org_jetbrains_skia_GraphicsKt__1nGetFontCacheLimit = () => {}
export const org_jetbrains_skia_GraphicsKt__1nGetFontCacheUsed = () => {}
export const org_jetbrains_skia_GraphicsKt__1nGetResourceCacheSingleAllocationByteLimit = () => {}
export const org_jetbrains_skia_GraphicsKt__1nGetResourceCacheTotalByteLimit = () => {}
export const org_jetbrains_skia_GraphicsKt__1nGetResourceCacheTotalBytesUsed = () => {}
export const org_jetbrains_skia_GraphicsKt__1nPurgeAllCaches = () => {}
export const org_jetbrains_skia_GraphicsKt__1nPurgeFontCache = () => {}
export const org_jetbrains_skia_GraphicsKt__1nPurgeResourceCache = () => {}
export const org_jetbrains_skia_GraphicsKt__1nSetFontCacheCountLimit = () => {}
export const org_jetbrains_skia_GraphicsKt__1nSetFontCacheLimit = () => {}
export const org_jetbrains_skia_GraphicsKt__1nSetResourceCacheSingleAllocationByteLimit = () => {}
export const org_jetbrains_skia_GraphicsKt__1nSetResourceCacheTotalByteLimit = () => {}
export const org_jetbrains_skia_Image__1nEncodeToData = () => {}
export const org_jetbrains_skia_Image__1nMakeFromBitmap = () => {}
export const org_jetbrains_skia_Image__1nMakeFromEncoded = () => {}
export const org_jetbrains_skia_Image__1nMakeFromPixmap = () => {}
export const org_jetbrains_skia_Image__1nMakeRaster = () => {}
export const org_jetbrains_skia_Image__1nMakeRasterData = () => {}
export const org_jetbrains_skia_Image__1nPeekPixelsToPixmap = () => {}
export const org_jetbrains_skia_Image__1nReadPixelsBitmap = () => {}
export const org_jetbrains_skia_Image__1nReadPixelsPixmap = () => {}
export const org_jetbrains_skia_Image__1nScalePixels = () => {}
export const org_jetbrains_skia_Image__1nGetImageInfo = () => {}
export const org_jetbrains_skia_Image__1nMakeShader = () => {}
export const org_jetbrains_skia_Image__1nPeekPixels = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeArithmetic = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeBlend = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeBlur = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeColorFilter = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeCompose = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeDilate = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeDisplacementMap = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeDistantLitDiffuse = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeDistantLitSpecular = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeDropShadow = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeDropShadowOnly = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeErode = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeImage = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeMagnifier = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeMatrixConvolution = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeMatrixTransform = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeMerge = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeOffset = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakePicture = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakePointLitDiffuse = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakePointLitSpecular = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeRuntimeShader = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeRuntimeShaderFromArray = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeShader = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeSpotLitDiffuse = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeSpotLitSpecular = () => {}
export const org_jetbrains_skia_ImageFilter__1nMakeTile = () => {}
export const org_jetbrains_skia_ManagedString__1nAppend = () => {}
export const org_jetbrains_skia_ManagedString__1nInsert = () => {}
export const org_jetbrains_skia_ManagedString__1nMake = () => {}
export const org_jetbrains_skia_ManagedString__1nRemove = () => {}
export const org_jetbrains_skia_ManagedString__1nRemoveSuffix = () => {}
export const org_jetbrains_skia_ManagedString__nStringData = () => {}
export const org_jetbrains_skia_ManagedString__nStringSize = () => {}
export const org_jetbrains_skia_ManagedString__1nGetFinalizer = () => {}
export const org_jetbrains_skia_MaskFilter__1nMakeBlur = () => {}
export const org_jetbrains_skia_MaskFilter__1nMakeClip = () => {}
export const org_jetbrains_skia_MaskFilter__1nMakeGamma = () => {}
export const org_jetbrains_skia_MaskFilter__1nMakeShader = () => {}
export const org_jetbrains_skia_MaskFilter__1nMakeTable = () => {}
export const org_jetbrains_skia_Paint__1nGetBlendMode = () => {}
export const org_jetbrains_skia_Paint__1nGetColor4f = () => {}
export const org_jetbrains_skia_Paint__1nGetColorFilter = () => {}
export const org_jetbrains_skia_Paint__1nGetImageFilter = () => {}
export const org_jetbrains_skia_Paint__1nGetMaskFilter = () => {}
export const org_jetbrains_skia_Paint__1nGetMode = () => {}
export const org_jetbrains_skia_Paint__1nGetPathEffect = () => {}
export const org_jetbrains_skia_Paint__1nGetShader = () => {}
export const org_jetbrains_skia_Paint__1nGetStrokeCap = () => {}
export const org_jetbrains_skia_Paint__1nGetStrokeJoin = () => {}
export const org_jetbrains_skia_Paint__1nGetStrokeMiter = () => {}
export const org_jetbrains_skia_Paint__1nGetStrokeWidth = () => {}
export const org_jetbrains_skia_Paint__1nHasNothingToDraw = () => {}
export const org_jetbrains_skia_Paint__1nIsAntiAlias = () => {}
export const org_jetbrains_skia_Paint__1nIsDither = () => {}
export const org_jetbrains_skia_Paint__1nSetAntiAlias = () => {}
export const org_jetbrains_skia_Paint__1nSetBlendMode = () => {}
export const org_jetbrains_skia_Paint__1nSetColor = () => {}
export const org_jetbrains_skia_Paint__1nSetColor4f = () => {}
export const org_jetbrains_skia_Paint__1nSetColorFilter = () => {}
export const org_jetbrains_skia_Paint__1nSetDither = () => {}
export const org_jetbrains_skia_Paint__1nSetImageFilter = () => {}
export const org_jetbrains_skia_Paint__1nSetMaskFilter = () => {}
export const org_jetbrains_skia_Paint__1nSetMode = () => {}
export const org_jetbrains_skia_Paint__1nSetPathEffect = () => {}
export const org_jetbrains_skia_Paint__1nSetShader = () => {}
export const org_jetbrains_skia_Paint__1nSetStrokeCap = () => {}
export const org_jetbrains_skia_Paint__1nSetStrokeJoin = () => {}
export const org_jetbrains_skia_Paint__1nSetStrokeMiter = () => {}
export const org_jetbrains_skia_Paint__1nSetStrokeWidth = () => {}
export const org_jetbrains_skia_Paint__1nEquals = () => {}
export const org_jetbrains_skia_Paint__1nGetColor = () => {}
export const org_jetbrains_skia_Paint__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Paint__1nMake = () => {}
export const org_jetbrains_skia_Paint__1nMakeClone = () => {}
export const org_jetbrains_skia_Paint__1nReset = () => {}
export const org_jetbrains_skia_PaintFilterCanvas__1nGetOnFilterPaint = () => {}
export const org_jetbrains_skia_PaintFilterCanvas__1nInit = () => {}
export const org_jetbrains_skia_PaintFilterCanvas__1nMake = () => {}
export const org_jetbrains_skia_Path__1nAddArc = () => {}
export const org_jetbrains_skia_Path__1nAddCircle = () => {}
export const org_jetbrains_skia_Path__1nAddOval = () => {}
export const org_jetbrains_skia_Path__1nAddPath = () => {}
export const org_jetbrains_skia_Path__1nAddPathOffset = () => {}
export const org_jetbrains_skia_Path__1nAddPathTransform = () => {}
export const org_jetbrains_skia_Path__1nAddPoly = () => {}
export const org_jetbrains_skia_Path__1nAddRect = () => {}
export const org_jetbrains_skia_Path__1nAddRRect = () => {}
export const org_jetbrains_skia_Path__1nApproximateBytesUsed = () => {}
export const org_jetbrains_skia_Path__1nArcTo = () => {}
export const org_jetbrains_skia_Path__1nClosePath = () => {}
export const org_jetbrains_skia_Path__1nComputeTightBounds = () => {}
export const org_jetbrains_skia_Path__1nConicTo = () => {}
export const org_jetbrains_skia_Path__1nConservativelyContainsRect = () => {}
export const org_jetbrains_skia_Path__1nContains = () => {}
export const org_jetbrains_skia_Path__1nConvertConicToQuads = () => {}
export const org_jetbrains_skia_Path__1nCountVerbs = () => {}
export const org_jetbrains_skia_Path__1nCubicTo = () => {}
export const org_jetbrains_skia_Path__1nDump = () => {}
export const org_jetbrains_skia_Path__1nDumpHex = () => {}
export const org_jetbrains_skia_Path__1nEllipticalArcTo = () => {}
export const org_jetbrains_skia_Path__1nGetBounds = () => {}
export const org_jetbrains_skia_Path__1nGetFillMode = () => {}
export const org_jetbrains_skia_Path__1nGetLastPt = () => {}
export const org_jetbrains_skia_Path__1nGetPoint = () => {}
export const org_jetbrains_skia_Path__1nGetPoints = () => {}
export const org_jetbrains_skia_Path__1nGetPointsCount = () => {}
export const org_jetbrains_skia_Path__1nGetSegmentMasks = () => {}
export const org_jetbrains_skia_Path__1nGetVerbs = () => {}
export const org_jetbrains_skia_Path__1nIncReserve = () => {}
export const org_jetbrains_skia_Path__1nIsConvex = () => {}
export const org_jetbrains_skia_Path__1nIsCubicDegenerate = () => {}
export const org_jetbrains_skia_Path__1nIsEmpty = () => {}
export const org_jetbrains_skia_Path__1nIsFinite = () => {}
export const org_jetbrains_skia_Path__1nIsInterpolatable = () => {}
export const org_jetbrains_skia_Path__1nIsLastContourClosed = () => {}
export const org_jetbrains_skia_Path__1nIsLineDegenerate = () => {}
export const org_jetbrains_skia_Path__1nIsOval = () => {}
export const org_jetbrains_skia_Path__1nIsQuadDegenerate = () => {}
export const org_jetbrains_skia_Path__1nIsRect = () => {}
export const org_jetbrains_skia_Path__1nIsRRect = () => {}
export const org_jetbrains_skia_Path__1nIsValid = () => {}
export const org_jetbrains_skia_Path__1nLineTo = () => {}
export const org_jetbrains_skia_Path__1nMakeCombining = () => {}
export const org_jetbrains_skia_Path__1nMakeFromBytes = () => {}
export const org_jetbrains_skia_Path__1nMakeFromSVGString = () => {}
export const org_jetbrains_skia_Path__1nMakeLerp = () => {}
export const org_jetbrains_skia_Path__1nMaybeGetAsLine = () => {}
export const org_jetbrains_skia_Path__1nMoveTo = () => {}
export const org_jetbrains_skia_Path__1nOffset = () => {}
export const org_jetbrains_skia_Path__1nQuadTo = () => {}
export const org_jetbrains_skia_Path__1nRConicTo = () => {}
export const org_jetbrains_skia_Path__1nRCubicTo = () => {}
export const org_jetbrains_skia_Path__1nREllipticalArcTo = () => {}
export const org_jetbrains_skia_Path__1nReverseAddPath = () => {}
export const org_jetbrains_skia_Path__1nRewind = () => {}
export const org_jetbrains_skia_Path__1nRLineTo = () => {}
export const org_jetbrains_skia_Path__1nRMoveTo = () => {}
export const org_jetbrains_skia_Path__1nRQuadTo = () => {}
export const org_jetbrains_skia_Path__1nSerializeToBytes = () => {}
export const org_jetbrains_skia_Path__1nSetFillMode = () => {}
export const org_jetbrains_skia_Path__1nSetLastPt = () => {}
export const org_jetbrains_skia_Path__1nTangentArcTo = () => {}
export const org_jetbrains_skia_Path__1nTransform = () => {}
export const org_jetbrains_skia_Path__1nUpdateBoundsCache = () => {}
export const org_jetbrains_skia_Path__1nEquals = () => {}
export const org_jetbrains_skia_Path__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Path__1nGetGenerationId = () => {}
export const org_jetbrains_skia_Path__1nIsVolatile = () => {}
export const org_jetbrains_skia_Path__1nMake = () => {}
export const org_jetbrains_skia_Path__1nReset = () => {}
export const org_jetbrains_skia_Path__1nSetVolatile = () => {}
export const org_jetbrains_skia_Path__1nSwap = () => {}
export const org_jetbrains_skia_PathEffect__1nMakeCorner = () => {}
export const org_jetbrains_skia_PathEffect__1nMakeDash = () => {}
export const org_jetbrains_skia_PathEffect__1nMakeDiscrete = () => {}
export const org_jetbrains_skia_PathEffect__1nMakeLine2D = () => {}
export const org_jetbrains_skia_PathEffect__1nMakePath1D = () => {}
export const org_jetbrains_skia_PathEffect__1nMakePath2D = () => {}
export const org_jetbrains_skia_PathEffect__1nMakeSum = () => {}
export const org_jetbrains_skia_PathEffect__1nMakeCompose = () => {}
export const org_jetbrains_skia_PathMeasure__1nGetLength = () => {}
export const org_jetbrains_skia_PathMeasure__1nGetMatrix = () => {}
export const org_jetbrains_skia_PathMeasure__1nGetPosition = () => {}
export const org_jetbrains_skia_PathMeasure__1nGetRSXform = () => {}
export const org_jetbrains_skia_PathMeasure__1nGetSegment = () => {}
export const org_jetbrains_skia_PathMeasure__1nGetTangent = () => {}
export const org_jetbrains_skia_PathMeasure__1nIsClosed = () => {}
export const org_jetbrains_skia_PathMeasure__1nMakePath = () => {}
export const org_jetbrains_skia_PathMeasure__1nNextContour = () => {}
export const org_jetbrains_skia_PathMeasure__1nSetPath = () => {}
export const org_jetbrains_skia_PathMeasure__1nGetFinalizer = () => {}
export const org_jetbrains_skia_PathMeasure__1nMake = () => {}
export const org_jetbrains_skia_PathSegmentIterator__1nMake = () => {}
export const org_jetbrains_skia_PathSegmentIterator__1nGetFinalizer = () => {}
export const org_jetbrains_skia_PathSegmentIterator__1nNext = () => {}
export const org_jetbrains_skia_PathUtils__1nFillPathWithPaint = () => {}
export const org_jetbrains_skia_PathUtils__1nFillPathWithPaintCull = () => {}
export const org_jetbrains_skia_Picture__1nGetApproximateBytesUsed = () => {}
export const org_jetbrains_skia_Picture__1nGetApproximateOpCount = () => {}
export const org_jetbrains_skia_Picture__1nGetCullRect = () => {}
export const org_jetbrains_skia_Picture__1nGetUniqueId = () => {}
export const org_jetbrains_skia_Picture__1nMakePlaceholder = () => {}
export const org_jetbrains_skia_Picture__1nMakeShader = () => {}
export const org_jetbrains_skia_Picture__1nPlayback = () => {}
export const org_jetbrains_skia_Picture__1nSerializeToData = () => {}
export const org_jetbrains_skia_Picture__1nMakeFromData = () => {}
export const org_jetbrains_skia_PictureRecorder__1nBeginRecording = () => {}
export const org_jetbrains_skia_PictureRecorder__1nFinishRecordingAsDrawable = () => {}
export const org_jetbrains_skia_PictureRecorder__1nFinishRecordingAsPicture = () => {}
export const org_jetbrains_skia_PictureRecorder__1nFinishRecordingAsPictureWithCull = () => {}
export const org_jetbrains_skia_PictureRecorder__1nGetRecordingCanvas = () => {}
export const org_jetbrains_skia_PictureRecorder__1nGetFinalizer = () => {}
export const org_jetbrains_skia_PictureRecorder__1nMake = () => {}
export const org_jetbrains_skia_PixelRef__1nGetHeight = () => {}
export const org_jetbrains_skia_PixelRef__1nGetWidth = () => {}
export const org_jetbrains_skia_PixelRef__1nGetGenerationId = () => {}
export const org_jetbrains_skia_PixelRef__1nGetRowBytes = () => {}
export const org_jetbrains_skia_PixelRef__1nIsImmutable = () => {}
export const org_jetbrains_skia_PixelRef__1nNotifyPixelsChanged = () => {}
export const org_jetbrains_skia_PixelRef__1nSetImmutable = () => {}
export const org_jetbrains_skia_Pixmap__1nErase = () => {}
export const org_jetbrains_skia_Pixmap__1nEraseSubset = () => {}
export const org_jetbrains_skia_Pixmap__1nGetAddr = () => {}
export const org_jetbrains_skia_Pixmap__1nGetAddrAt = () => {}
export const org_jetbrains_skia_Pixmap__1nGetAlphaF = () => {}
export const org_jetbrains_skia_Pixmap__1nGetInfo = () => {}
export const org_jetbrains_skia_Pixmap__1nMakeNull = () => {}
export const org_jetbrains_skia_Pixmap__1nReadPixels = () => {}
export const org_jetbrains_skia_Pixmap__1nReadPixelsFromPoint = () => {}
export const org_jetbrains_skia_Pixmap__1nReadPixelsToPixmap = () => {}
export const org_jetbrains_skia_Pixmap__1nReadPixelsToPixmapFromPoint = () => {}
export const org_jetbrains_skia_Pixmap__1nResetWithInfo = () => {}
export const org_jetbrains_skia_Pixmap__1nScalePixels = () => {}
export const org_jetbrains_skia_Pixmap__1nSetColorSpace = () => {}
export const org_jetbrains_skia_Pixmap__1nComputeByteSize = () => {}
export const org_jetbrains_skia_Pixmap__1nComputeIsOpaque = () => {}
export const org_jetbrains_skia_Pixmap__1nExtractSubset = () => {}
export const org_jetbrains_skia_Pixmap__1nGetColor = () => {}
export const org_jetbrains_skia_Pixmap__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Pixmap__1nGetRowBytes = () => {}
export const org_jetbrains_skia_Pixmap__1nGetRowBytesAsPixels = () => {}
export const org_jetbrains_skia_Pixmap__1nMake = () => {}
export const org_jetbrains_skia_Pixmap__1nReset = () => {}
export const org_jetbrains_skia_Region__1nComputeRegionComplexity = () => {}
export const org_jetbrains_skia_Region__1nContainsIPoint = () => {}
export const org_jetbrains_skia_Region__1nContainsIRect = () => {}
export const org_jetbrains_skia_Region__1nContainsRegion = () => {}
export const org_jetbrains_skia_Region__1nGetBoundaryPath = () => {}
export const org_jetbrains_skia_Region__1nGetBounds = () => {}
export const org_jetbrains_skia_Region__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Region__1nIntersectsIRect = () => {}
export const org_jetbrains_skia_Region__1nIntersectsRegion = () => {}
export const org_jetbrains_skia_Region__1nIsComplex = () => {}
export const org_jetbrains_skia_Region__1nIsEmpty = () => {}
export const org_jetbrains_skia_Region__1nIsRect = () => {}
export const org_jetbrains_skia_Region__1nMake = () => {}
export const org_jetbrains_skia_Region__1nOpIRect = () => {}
export const org_jetbrains_skia_Region__1nOpIRectRegion = () => {}
export const org_jetbrains_skia_Region__1nOpRegion = () => {}
export const org_jetbrains_skia_Region__1nOpRegionIRect = () => {}
export const org_jetbrains_skia_Region__1nOpRegionRegion = () => {}
export const org_jetbrains_skia_Region__1nQuickContains = () => {}
export const org_jetbrains_skia_Region__1nQuickRejectIRect = () => {}
export const org_jetbrains_skia_Region__1nQuickRejectRegion = () => {}
export const org_jetbrains_skia_Region__1nSet = () => {}
export const org_jetbrains_skia_Region__1nSetEmpty = () => {}
export const org_jetbrains_skia_Region__1nSetPath = () => {}
export const org_jetbrains_skia_Region__1nSetRect = () => {}
export const org_jetbrains_skia_Region__1nSetRects = () => {}
export const org_jetbrains_skia_Region__1nSetRegion = () => {}
export const org_jetbrains_skia_Region__1nTranslate = () => {}
export const org_jetbrains_skia_RuntimeEffect__1nMakeForColorFilter = () => {}
export const org_jetbrains_skia_RuntimeEffect__1nMakeForShader = () => {}
export const org_jetbrains_skia_RuntimeEffect__1nMakeShader = () => {}
export const org_jetbrains_skia_RuntimeEffect__1Result_nDestroy = () => {}
export const org_jetbrains_skia_RuntimeEffect__1Result_nGetError = () => {}
export const org_jetbrains_skia_RuntimeEffect__1Result_nGetPtr = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nChildColorFilter = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nChildShader = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nMakeFromRuntimeEffect = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nMakeShader = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloat = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloat2 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloat3 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloat4 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloatMatrix22 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloatMatrix33 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloatMatrix44 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformInt = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformInt2 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformInt3 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nUniformInt4 = () => {}
export const org_jetbrains_skia_RuntimeShaderBuilder__1nGetFinalizer = () => {}
export const org_jetbrains_skia_Shader__1nMakeBlend = () => {}
export const org_jetbrains_skia_Shader__1nMakeColor = () => {}
export const org_jetbrains_skia_Shader__1nMakeColorCS = () => {}
export const org_jetbrains_skia_Shader__1nMakeFractalNoise = () => {}
export const org_jetbrains_skia_Shader__1nMakeLinearGradient = () => {}
export const org_jetbrains_skia_Shader__1nMakeLinearGradientCS = () => {}
export const org_jetbrains_skia_Shader__1nMakeRadialGradient = () => {}
export const org_jetbrains_skia_Shader__1nMakeRadialGradientCS = () => {}
export const org_jetbrains_skia_Shader__1nMakeSweepGradient = () => {}
export const org_jetbrains_skia_Shader__1nMakeSweepGradientCS = () => {}
export const org_jetbrains_skia_Shader__1nMakeTurbulence = () => {}
export const org_jetbrains_skia_Shader__1nMakeTwoPointConicalGradient = () => {}
export const org_jetbrains_skia_Shader__1nMakeTwoPointConicalGradientCS = () => {}
export const org_jetbrains_skia_Shader__1nMakeWithColorFilter = () => {}
export const org_jetbrains_skia_Shader__1nMakeEmpty = () => {}
export const org_jetbrains_skia_ShadowUtils__1nComputeTonalAmbientColor = () => {}
export const org_jetbrains_skia_ShadowUtils__1nComputeTonalSpotColor = () => {}
export const org_jetbrains_skia_ShadowUtils__1nDrawShadow = () => {}
export const org_jetbrains_skia_StdVectorDecoder__1nDisposeArray = () => {}
export const org_jetbrains_skia_StdVectorDecoder__1nGetArraySize = () => {}
export const org_jetbrains_skia_StdVectorDecoder__1nReleaseElement = () => {}
export const org_jetbrains_skia_Surface__1nDraw = () => {}
export const org_jetbrains_skia_Surface__1nFlushAndSubmit = () => {}
export const org_jetbrains_skia_Surface__1nGenerationId = () => {}
export const org_jetbrains_skia_Surface__1nGetCanvas = () => {}
export const org_jetbrains_skia_Surface__1nGetRecordingContext = () => {}
export const org_jetbrains_skia_Surface__1nMakeFromBackendRenderTarget = () => {}
export const org_jetbrains_skia_Surface__1nMakeFromMTKView = () => {}
export const org_jetbrains_skia_Surface__1nMakeImageSnapshot = () => {}
export const org_jetbrains_skia_Surface__1nMakeImageSnapshotR = () => {}
export const org_jetbrains_skia_Surface__1nMakeNull = () => {}
export const org_jetbrains_skia_Surface__1nMakeRaster = () => {}
export const org_jetbrains_skia_Surface__1nMakeRasterDirect = () => {}
export const org_jetbrains_skia_Surface__1nMakeRasterDirectWithPixmap = () => {}
export const org_jetbrains_skia_Surface__1nMakeRasterN32Premul = () => {}
export const org_jetbrains_skia_Surface__1nMakeRenderTarget = () => {}
export const org_jetbrains_skia_Surface__1nMakeSurface = () => {}
export const org_jetbrains_skia_Surface__1nMakeSurfaceI = () => {}
export const org_jetbrains_skia_Surface__1nNotifyContentWillChange = () => {}
export const org_jetbrains_skia_Surface__1nPeekPixels = () => {}
export const org_jetbrains_skia_Surface__1nReadPixelsToPixmap = () => {}
export const org_jetbrains_skia_Surface__1nUnique = () => {}
export const org_jetbrains_skia_Surface__1nWritePixelsFromPixmap = () => {}
export const org_jetbrains_skia_Surface__1nFlush = () => {}
export const org_jetbrains_skia_Surface__1nGetHeight = () => {}
export const org_jetbrains_skia_Surface__1nGetImageInfo = () => {}
export const org_jetbrains_skia_Surface__1nGetWidth = () => {}
export const org_jetbrains_skia_Surface__1nReadPixels = () => {}
export const org_jetbrains_skia_Surface__1nWritePixels = () => {}
export const org_jetbrains_skia_TextBlob__1nBounds = () => {}
export const org_jetbrains_skia_TextBlob__1nGetBlockBounds = () => {}
export const org_jetbrains_skia_TextBlob__1nGetClusters = () => {}
export const org_jetbrains_skia_TextBlob__1nGetClustersLength = () => {}
export const org_jetbrains_skia_TextBlob__1nGetFirstBaseline = () => {}
export const org_jetbrains_skia_TextBlob__1nGetGlyphs = () => {}
export const org_jetbrains_skia_TextBlob__1nGetGlyphsLength = () => {}
export const org_jetbrains_skia_TextBlob__1nGetIntercepts = () => {}
export const org_jetbrains_skia_TextBlob__1nGetInterceptsLength = () => {}
export const org_jetbrains_skia_TextBlob__1nGetLastBaseline = () => {}
export const org_jetbrains_skia_TextBlob__1nGetPositions = () => {}
export const org_jetbrains_skia_TextBlob__1nGetPositionsLength = () => {}
export const org_jetbrains_skia_TextBlob__1nGetTightBounds = () => {}
export const org_jetbrains_skia_TextBlob__1nMakeFromPos = () => {}
export const org_jetbrains_skia_TextBlob__1nMakeFromPosH = () => {}
export const org_jetbrains_skia_TextBlob__1nMakeFromRSXform = () => {}
export const org_jetbrains_skia_TextBlob_Iter__1nCreate = () => {}
export const org_jetbrains_skia_TextBlob_Iter__1nFetch = () => {}
export const org_jetbrains_skia_TextBlob_Iter__1nGetFinalizer = () => {}
export const org_jetbrains_skia_TextBlob_Iter__1nGetGlyphCount = () => {}
export const org_jetbrains_skia_TextBlob_Iter__1nGetGlyphs = () => {}
export const org_jetbrains_skia_TextBlob_Iter__1nGetTypeface = () => {}
export const org_jetbrains_skia_TextBlob_Iter__1nHasNext = () => {}
export const org_jetbrains_skia_TextBlob__1nGetFinalizer = () => {}
export const org_jetbrains_skia_TextBlob__1nGetUniqueId = () => {}
export const org_jetbrains_skia_TextBlob__1nMakeFromData = () => {}
export const org_jetbrains_skia_TextBlob__1nSerializeToData = () => {}
export const org_jetbrains_skia_TextBlobBuilder__1nAppendRun = () => {}
export const org_jetbrains_skia_TextBlobBuilder__1nAppendRunPos = () => {}
export const org_jetbrains_skia_TextBlobBuilder__1nAppendRunPosH = () => {}
export const org_jetbrains_skia_TextBlobBuilder__1nAppendRunRSXform = () => {}
export const org_jetbrains_skia_TextBlobBuilder__1nBuild = () => {}
export const org_jetbrains_skia_TextBlobBuilder__1nGetFinalizer = () => {}
export const org_jetbrains_skia_TextBlobBuilder__1nMake = () => {}
export const org_jetbrains_skia_TextLine__1nGetAscent = () => {}
export const org_jetbrains_skia_TextLine__1nGetBreakOffsets = () => {}
export const org_jetbrains_skia_TextLine__1nGetBreakOffsetsCount = () => {}
export const org_jetbrains_skia_TextLine__1nGetBreakPositions = () => {}
export const org_jetbrains_skia_TextLine__1nGetBreakPositionsCount = () => {}
export const org_jetbrains_skia_TextLine__1nGetCapHeight = () => {}
export const org_jetbrains_skia_TextLine__1nGetCoordAtOffset = () => {}
export const org_jetbrains_skia_TextLine__1nGetDescent = () => {}
export const org_jetbrains_skia_TextLine__1nGetLeading = () => {}
export const org_jetbrains_skia_TextLine__1nGetLeftOffsetAtCoord = () => {}
export const org_jetbrains_skia_TextLine__1nGetOffsetAtCoord = () => {}
export const org_jetbrains_skia_TextLine__1nGetRunPositions = () => {}
export const org_jetbrains_skia_TextLine__1nGetRunPositionsCount = () => {}
export const org_jetbrains_skia_TextLine__1nGetTextBlob = () => {}
export const org_jetbrains_skia_TextLine__1nGetXHeight = () => {}
export const org_jetbrains_skia_TextLine__1nGetFinalizer = () => {}
export const org_jetbrains_skia_TextLine__1nGetGlyphs = () => {}
export const org_jetbrains_skia_TextLine__1nGetGlyphsLength = () => {}
export const org_jetbrains_skia_TextLine__1nGetHeight = () => {}
export const org_jetbrains_skia_TextLine__1nGetPositions = () => {}
export const org_jetbrains_skia_TextLine__1nGetWidth = () => {}
export const org_jetbrains_skia_Typeface__1nGetFamilyName = () => {}
export const org_jetbrains_skia_Typeface__1nGetFamilyNames = () => {}
export const org_jetbrains_skia_Typeface__1nGetFontStyle = () => {}
export const org_jetbrains_skia_Typeface__1nGetGlyphsCount = () => {}
export const org_jetbrains_skia_Typeface__1nGetKerningPairAdjustments = () => {}
export const org_jetbrains_skia_Typeface__1nGetTableData = () => {}
export const org_jetbrains_skia_Typeface__1nGetTablesCount = () => {}
export const org_jetbrains_skia_Typeface__1nGetTableSize = () => {}
export const org_jetbrains_skia_Typeface__1nGetTableTags = () => {}
export const org_jetbrains_skia_Typeface__1nGetTableTagsCount = () => {}
export const org_jetbrains_skia_Typeface__1nGetUnitsPerEm = () => {}
export const org_jetbrains_skia_Typeface__1nGetVariationAxes = () => {}
export const org_jetbrains_skia_Typeface__1nGetVariationAxesCount = () => {}
export const org_jetbrains_skia_Typeface__1nGetVariations = () => {}
export const org_jetbrains_skia_Typeface__1nGetVariationsCount = () => {}
export const org_jetbrains_skia_Typeface__1nIsFixedPitch = () => {}
export const org_jetbrains_skia_Typeface__1nMakeClone = () => {}
export const org_jetbrains_skia_Typeface__1nMakeFromData = () => {}
export const org_jetbrains_skia_Typeface__1nMakeFromFile = () => {}
export const org_jetbrains_skia_Typeface__1nMakeFromName = () => {}
export const org_jetbrains_skia_Typeface__1nEquals = () => {}
export const org_jetbrains_skia_Typeface__1nGetBounds = () => {}
export const org_jetbrains_skia_Typeface__1nGetUniqueId = () => {}
export const org_jetbrains_skia_Typeface__1nGetUTF32Glyph = () => {}
export const org_jetbrains_skia_Typeface__1nGetUTF32Glyphs = () => {}
export const org_jetbrains_skia_Typeface__1nMakeDefault = () => {}
export const org_jetbrains_skia_U16String__1nGetFinalizer = () => {}
export const org_jetbrains_skia_icu_Unicode_charDirection = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nDefaultFallback = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nDefaultFallbackChar = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nFindTypefaces = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nGetFallbackManager = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nGetFontManagersCount = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nGetParagraphCache = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nMake = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nSetAssetFontManager = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nSetDefaultFontManager = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nSetDynamicFontManager = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nSetEnableFallback = () => {}
export const org_jetbrains_skia_paragraph_FontCollection__1nSetTestFontManager = () => {}
export const org_jetbrains_skia_paragraph_LineMetrics__1nDisposeArray = () => {}
export const org_jetbrains_skia_paragraph_LineMetrics__1nGetArrayElement = () => {}
export const org_jetbrains_skia_paragraph_LineMetrics__1nGetArraySize = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nDidExceedMaxLines = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetAlphabeticBaseline = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetGlyphPositionAtCoordinate = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetHeight = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetIdeographicBaseline = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetLineMetrics = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetLineNumber = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetLongestLine = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetMaxIntrinsicWidth = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetMaxWidth = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetMinIntrinsicWidth = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetRectsForPlaceholders = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetRectsForRange = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetUnresolvedGlyphsCount = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetWordBoundary = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nLayout = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nMarkDirty = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nPaint = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nUpdateAlignment = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nUpdateBackgroundPaint = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nUpdateFontSize = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nUpdateForegroundPaint = () => {}
export const org_jetbrains_skia_paragraph_Paragraph__1nGetFinalizer = () => {}
export const org_jetbrains_skia_paragraph_ParagraphBuilder__1nAddPlaceholder = () => {}
export const org_jetbrains_skia_paragraph_ParagraphBuilder__1nAddText = () => {}
export const org_jetbrains_skia_paragraph_ParagraphBuilder__1nBuild = () => {}
export const org_jetbrains_skia_paragraph_ParagraphBuilder__1nMake = () => {}
export const org_jetbrains_skia_paragraph_ParagraphBuilder__1nPopStyle = () => {}
export const org_jetbrains_skia_paragraph_ParagraphBuilder__1nPushStyle = () => {}
export const org_jetbrains_skia_paragraph_ParagraphBuilder__1nGetFinalizer = () => {}
export const org_jetbrains_skia_paragraph_ParagraphCache__1nAbandon = () => {}
export const org_jetbrains_skia_paragraph_ParagraphCache__1nFindParagraph = () => {}
export const org_jetbrains_skia_paragraph_ParagraphCache__1nGetCount = () => {}
export const org_jetbrains_skia_paragraph_ParagraphCache__1nPrintStatistics = () => {}
export const org_jetbrains_skia_paragraph_ParagraphCache__1nReset = () => {}
export const org_jetbrains_skia_paragraph_ParagraphCache__1nSetEnabled = () => {}
export const org_jetbrains_skia_paragraph_ParagraphCache__1nUpdateParagraph = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nDisableHinting = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nEquals = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetAlignment = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetDirection = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetEdging = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetEffectiveAlignment = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetEllipsis = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetHeightMode = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetHinting = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetMaxLinesCount = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetStrutStyle = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetSubpixel = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetTextIndent = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetTextStyle = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nIsHintingEnabled = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetAlignment = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetDirection = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetEllipsis = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetFontRastrSettings = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetHeight = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetHeightMode = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetMaxLinesCount = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetStrutStyle = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetTextIndent = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nSetTextStyle = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetFinalizer = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nGetHeight = () => {}
export const org_jetbrains_skia_paragraph_ParagraphStyle__1nMake = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nGetFontFamilies = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nGetFontSize = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nGetFontStyle = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nGetLeading = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nIsEnabled = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nIsHalfLeading = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nIsHeightForced = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nIsHeightOverridden = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetFontSize = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetFontStyle = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetHalfLeading = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetHeightForced = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetHeightOverridden = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetLeading = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nEquals = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nGetFinalizer = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nGetHeight = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nMake = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetEnabled = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetFontFamilies = () => {}
export const org_jetbrains_skia_paragraph_StrutStyle__1nSetHeight = () => {}
export const org_jetbrains_skia_paragraph_TextBox__1nDisposeArray = () => {}
export const org_jetbrains_skia_paragraph_TextBox__1nGetArrayElement = () => {}
export const org_jetbrains_skia_paragraph_TextBox__1nGetArraySize = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nAddFontFeature = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nAddShadow = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nAttributeEquals = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nClearFontFeatures = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nClearShadows = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetBackground = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetBaselineMode = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetColor = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetDecorationStyle = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetFontFeatures = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetFontFeaturesSize = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetFontMetrics = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetForeground = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetLetterSpacing = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetLocale = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetShadows = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetShadowsCount = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetTypeface = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetWordSpacing = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nIsPlaceholder = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetBackground = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetBaselineMode = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetColor = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetDecorationStyle = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetFontFamilies = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetForeground = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetLetterSpacing = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetLocale = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetPlaceholder = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetTypeface = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetWordSpacing = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nEquals = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetBaselineShift = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetFinalizer = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetFontFamilies = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetFontSize = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetFontStyle = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetHalfLeading = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nGetHeight = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nMake = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetBaselineShift = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetFontSize = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetFontStyle = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetHalfLeading = () => {}
export const org_jetbrains_skia_paragraph_TextStyle__1nSetHeight = () => {}
export const org_jetbrains_skia_paragraph_TypefaceFontProvider__1nRegisterTypeface = () => {}
export const org_jetbrains_skia_paragraph_TypefaceFontProvider__1nMake = () => {}
export const org_jetbrains_skia_shaper_FontMgrRunIterator__1nGetCurrentFont = () => {}
export const org_jetbrains_skia_shaper_FontMgrRunIterator__1nMake = () => {}
export const org_jetbrains_skia_shaper_HbIcuScriptRunIterator__1nGetCurrentScriptTag = () => {}
export const org_jetbrains_skia_shaper_HbIcuScriptRunIterator__1nMake = () => {}
export const org_jetbrains_skia_shaper_IcuBidiRunIterator__1nGetCurrentLevel = () => {}
export const org_jetbrains_skia_shaper_IcuBidiRunIterator__1nMake = () => {}
export const org_jetbrains_skia_shaper_ManagedRunIterator__1nConsume = () => {}
export const org_jetbrains_skia_shaper_ManagedRunIterator__1nGetEndOfCurrentRun = () => {}
export const org_jetbrains_skia_shaper_ManagedRunIterator__1nGetFinalizer = () => {}
export const org_jetbrains_skia_shaper_ManagedRunIterator__1nIsAtEnd = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nMakeCoreText = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nMakePrimitive = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nMakeShapeDontWrapOrReorder = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nMakeShaperDrivenWrapper = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nMakeShapeThenWrap = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nShapeBlob = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nShapeLine = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nCreate = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nGetClusters = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nGetFinalizer = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nGetGlyphs = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nGetPositions = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nGetRunInfo = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nInit = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunHandler_1nSetOffset = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunIterator_1nCreateRunIterator = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunIterator_1nGetFinalizer = () => {}
export const org_jetbrains_skia_shaper_Shaper_RunIterator_1nInitRunIterator = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nGetFinalizer = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nMake = () => {}
export const org_jetbrains_skia_shaper_Shaper__1nShape = () => {}
export const org_jetbrains_skia_TextBlobBuilderRunHandler__1nMakeBlob = () => {}
export const org_jetbrains_skia_TextBlobBuilderRunHandler__1nGetFinalizer = () => {}
export const org_jetbrains_skia_TextBlobBuilderRunHandler__1nMake = () => {}
export const org_jetbrains_skia_skottie_Animation__1nGetDuration = () => {}
export const org_jetbrains_skia_skottie_Animation__1nGetFinalizer = () => {}
export const org_jetbrains_skia_skottie_Animation__1nGetFPS = () => {}
export const org_jetbrains_skia_skottie_Animation__1nGetInPoint = () => {}
export const org_jetbrains_skia_skottie_Animation__1nGetOutPoint = () => {}
export const org_jetbrains_skia_skottie_Animation__1nGetSize = () => {}
export const org_jetbrains_skia_skottie_Animation__1nGetVersion = () => {}
export const org_jetbrains_skia_skottie_Animation__1nMakeFromData = () => {}
export const org_jetbrains_skia_skottie_Animation__1nMakeFromFile = () => {}
export const org_jetbrains_skia_skottie_Animation__1nMakeFromString = () => {}
export const org_jetbrains_skia_skottie_Animation__1nRender = () => {}
export const org_jetbrains_skia_skottie_Animation__1nSeek = () => {}
export const org_jetbrains_skia_skottie_Animation__1nSeekFrame = () => {}
export const org_jetbrains_skia_skottie_Animation__1nSeekFrameTime = () => {}
export const org_jetbrains_skia_skottie_AnimationBuilder__1nBuildFromData = () => {}
export const org_jetbrains_skia_skottie_AnimationBuilder__1nBuildFromFile = () => {}
export const org_jetbrains_skia_skottie_AnimationBuilder__1nBuildFromString = () => {}
export const org_jetbrains_skia_skottie_AnimationBuilder__1nSetFontManager = () => {}
export const org_jetbrains_skia_skottie_AnimationBuilder__1nSetLogger = () => {}
export const org_jetbrains_skia_skottie_AnimationBuilder__1nGetFinalizer = () => {}
export const org_jetbrains_skia_skottie_AnimationBuilder__1nMake = () => {}
export const org_jetbrains_skia_skottie_Logger__1nMake = () => {}
export const org_jetbrains_skia_skottie_Logger__1nGetLogJson = () => {}
export const org_jetbrains_skia_skottie_Logger__1nGetLogLevel = () => {}
export const org_jetbrains_skia_skottie_Logger__1nGetLogMessage = () => {}
export const org_jetbrains_skia_skottie_Logger__1nInit = () => {}
export const org_jetbrains_skia_sksg_InvalidationController_nGetBounds = () => {}
export const org_jetbrains_skia_sksg_InvalidationController_nGetFinalizer = () => {}
export const org_jetbrains_skia_sksg_InvalidationController_nInvalidate = () => {}
export const org_jetbrains_skia_sksg_InvalidationController_nMake = () => {}
export const org_jetbrains_skia_sksg_InvalidationController_nReset = () => {}
export const org_jetbrains_skia_svg_SVGCanvasKt__1nMake = () => {}
export const org_jetbrains_skia_svg_SVGDOM__1nGetContainerSize = () => {}
export const org_jetbrains_skia_svg_SVGDOM__1nGetRoot = () => {}
export const org_jetbrains_skia_svg_SVGDOM__1nMakeFromData = () => {}
export const org_jetbrains_skia_svg_SVGDOM__1nRender = () => {}
export const org_jetbrains_skia_svg_SVGDOM__1nSetContainerSize = () => {}
export const org_jetbrains_skia_svg_SVGNode__1nGetTag = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nGetHeight = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nGetIntrinsicSize = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nGetPreserveAspectRatio = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nGetViewBox = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nGetWidth = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nGetX = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nGetY = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nSetHeight = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nSetPreserveAspectRatio = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nSetViewBox = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nSetWidth = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nSetX = () => {}
export const org_jetbrains_skia_svg_SVGSVG__1nSetY = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nFillByteArrayOf5 = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nFillDoubleArrayOf5 = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nFillFloatArrayOf5 = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nFillIntArrayOf5 = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nFillShortArrayOf5 = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__nStringByIndex = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nWriteArraysOfInts = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nCreateTestGlContext = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nGlContextGetFinalizer = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nMakeGlContextCurrent = () => {}
export const org_jetbrains_skiko_tests_TestHelpers__1nGlContextSwapBuffers = () => {}
export const org_jetbrains_skia_impl_Managed__invokeFinalizer = () => {}
export const free = () => {}
export const malloc = () => {}
export const org_jetbrains_skia_impl_RefCnt__getRefCount = () => {}
export const org_jetbrains_skia_impl_RefCnt__getFinalizer = () => {}
export const org_jetbrains_skia_OutputWStream__1nMake = () => {}
export const org_jetbrains_skia_OutputWStream__1nGetFinalizer = () => {}
export const skia_memGetByte = () => {}
export const skia_memGetChar = () => {}
export const skia_memGetDouble = () => {}
export const skia_memGetFloat = () => {}
export const skia_memGetInt = () => {}
export const skia_memGetShort = () => {}
export const skia_memSetByte = () => {}
export const skia_memSetChar = () => {}
export const skia_memSetDouble = () => {}
export const skia_memSetFloat = () => {}
export const skia_memSetInt = () => {}
export const skia_memSetShort = () => {}