#!/usr/bin/env bash
# Air cloud environment startup for kotlin-compiler-server.
#
# Installs the Amazon Corretto 17 JDK the Gradle build requires (the daemon JVM is
# pinned to Java 17 by gradle/gradle-daemon-jvm.properties, and every Kotlin/Java
# toolchain in this build additionally requires JvmVendorSpec.AMAZON), primes the
# Gradle dependency/build caches, and starts the Spring Boot compiler server.
#
# AIR_STARTUP_MODE=warmup  -> snapshot-baking run: do the expensive work and block
#                             on `healthcheck` so finished downloads/builds land in
#                             the snapshot.
# AIR_STARTUP_MODE=task    -> real task run: reuse the snapshot, start the server in
#                             the background and return promptly.
set -euo pipefail

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$REPO_ROOT"

log()  { printf '[startup] %s\n' "$*"; }
fail() { printf '[startup][error] %s\n' "$*" >&2; exit 1; }

if [ "${AIR_STARTUP_MODE:-}" = warmup ]; then WARMUP=1; else WARMUP=; fi
log "mode=${AIR_STARTUP_MODE:-task} repo=$REPO_ROOT"

# Corretto build pinned on purpose: it is the JDK 17 the Dockerfile/CI use, and a
# fixed version keeps the warm-up snapshot reproducible.
CORRETTO_VERSION=17.0.20.10.1
JDK_HOME="$HOME/.jdks/amazon-corretto-17"
ENV_FILE="$HOME/.air-kotlin-compiler-server-env.sh"
ENV_MARKER='# >>> kotlin-compiler-server air env >>>'
SERVER_PORT=8080
SERVER_LOG=/tmp/kotlin-compiler-server.log
SERVER_PID_FILE=/tmp/kotlin-compiler-server.pid
# Base image of the container ThreadLeakE2ETest builds through Testcontainers.
E2E_BASE_IMAGE=amazoncorretto:17-al2023

# ---------------------------------------------------------------- JDK -------

install_jdk() {
  if [ -x "$JDK_HOME/bin/javac" ]; then
    log "Amazon Corretto 17 already installed at $JDK_HOME"
    return
  fi

  local tarball archive_name url downloaded=
  archive_name="amazon-corretto-${CORRETTO_VERSION}-linux-x64.tar.gz"
  tarball=$(mktemp /tmp/corretto-XXXXXX.tar.gz)

  for url in \
    "https://cache-redirector.jetbrains.com/corretto.aws/downloads/resources/${CORRETTO_VERSION}/${archive_name}" \
    "https://corretto.aws/downloads/resources/${CORRETTO_VERSION}/${archive_name}"
  do
    log "downloading Amazon Corretto ${CORRETTO_VERSION} from ${url%%/downloads/*} ..."
    if curl -fsSL --retry 3 --retry-delay 5 -o "$tarball" "$url"; then
      downloaded=1
      break
    fi
    log "download failed from $url, trying next mirror"
  done
  [ -n "$downloaded" ] || fail "could not download Amazon Corretto ${CORRETTO_VERSION} from any mirror"

  local staging
  staging=$(mktemp -d /tmp/corretto-extract-XXXXXX)
  tar -xzf "$tarball" -C "$staging"
  rm -f "$tarball"

  local extracted
  extracted=$(find "$staging" -maxdepth 1 -mindepth 1 -type d | sort | head -1)
  [ -x "$extracted/bin/javac" ] || fail "downloaded Corretto archive has no bin/javac"

  mkdir -p "$(dirname "$JDK_HOME")"
  rm -rf "$JDK_HOME"
  mv "$extracted" "$JDK_HOME"
  rm -rf "$staging"

  grep -q 'Amazon' "$JDK_HOME/release" \
    || fail "installed JDK is not an Amazon Corretto build; the AMAZON toolchain requirement would fail"
  log "installed $("$JDK_HOME/bin/java" -version 2>&1 | grep -v '^Picked up' | head -1) at $JDK_HOME"
}

# JAVA_HOME must survive this script: the launch runs it as a child process, so the
# agent's login shell only sees what we write into a sourced profile hook.
persist_env() {
  cat > "$ENV_FILE" <<EOF
# Generated by .air/cloud/startup.sh — Amazon Corretto 17 for the Gradle build.
export JAVA_HOME="$JDK_HOME"
case ":\$PATH:" in
  *":$JDK_HOME/bin:"*) ;;
  *) export PATH="$JDK_HOME/bin:\$PATH" ;;
esac
EOF

  local profile
  profile=""
  for candidate in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
    if [ -f "$candidate" ]; then profile="$candidate"; break; fi
  done
  if [ -z "$profile" ]; then
    profile="$HOME/.profile"
    touch "$profile"
  fi

  local hook
  for hook in "$profile" "$HOME/.bashrc"; do
    [ -e "$hook" ] || touch "$hook"
    if ! grep -qF "$ENV_MARKER" "$hook"; then
      {
        printf '\n%s\n' "$ENV_MARKER"
        printf '[ -f "%s" ] && . "%s"\n' "$ENV_FILE" "$ENV_FILE"
        printf '%s\n' '# <<< kotlin-compiler-server air env <<<'
      } >> "$hook"
      log "hooked $ENV_FILE into $hook"
    fi
  done
}

# -------------------------------------------------------------- caches ------

# Pull the image ThreadLeakE2ETest and Testcontainers need. Image layers are files on
# disk, so they are captured by the warm-up snapshot. Best effort: a task can still
# run the rest of the suite without Docker.
prime_docker_images() {
  if ! command -v docker >/dev/null 2>&1; then
    log "docker CLI not available — skipping image pre-pull (ThreadLeakE2ETest needs it)"
    return
  fi
  if ! docker info >/dev/null 2>&1; then
    log "docker daemon not reachable — skipping image pre-pull (ThreadLeakE2ETest needs it)"
    return
  fi

  log "pre-pulling $E2E_BASE_IMAGE ..."
  if docker pull "$E2E_BASE_IMAGE"; then
    log "pulled $E2E_BASE_IMAGE"
  else
    log "WARN: could not pull $E2E_BASE_IMAGE; ThreadLeakE2ETest will pull it on first run"
  fi

  # Testcontainers' resource reaper image, read from the resolved testcontainers jar
  # so it stays in sync with the version in gradle/libs.versions.toml.
  local tc_jar ryuk
  tc_jar=$(find "$HOME/.gradle/caches/modules-2/files-2.1/org.testcontainers/testcontainers" \
             -name 'testcontainers-*.jar' 2>/dev/null | sort | tail -1 || true)
  if [ -n "$tc_jar" ] && command -v unzip >/dev/null 2>&1; then
    ryuk=$(unzip -p "$tc_jar" testcontainers.properties 2>/dev/null \
             | sed -n 's/^ryuk\.container\.image=//p' | tr -d '\r' | head -1 || true)
    if [ -n "${ryuk:-}" ]; then
      log "pre-pulling Testcontainers reaper $ryuk ..."
      docker pull "$ryuk" || log "WARN: could not pull $ryuk"
    fi
  fi
}

build_project() {
  chmod +x ./gradlew

  # `build -x test` is the documented build (README). `testClasses` is added because
  # -x test would otherwise skip test compilation, and priming it means a task's first
  # `./gradlew test` only has to run the tests.
  log "gradle build: server, executors, Kotlin JVM/JS/Wasm library sets and test sources ..."
  ./gradlew build -x test testClasses :resource-server:testClasses \
    --console=plain --no-daemon \
    || fail "'./gradlew build -x test testClasses' failed — see the output above"
  log "gradle build finished"
}

# -------------------------------------------------------------- server ------

boot_jar() {
  find build/libs -maxdepth 1 -name 'kotlin-compiler-server-*-SNAPSHOT.jar' \
    ! -name '*-plain.jar' 2>/dev/null | sort | tail -1
}

start_server() {
  local jar
  jar=$(boot_jar)
  [ -n "$jar" ] || fail "boot jar not found in build/libs after the Gradle build"

  # Run from the repository root: application.properties points libraries.folder.* at
  # paths relative to it (e.g. ./<kotlinVersion>, ./<kotlinVersion>-js).
  log "starting compiler server from $jar on port $SERVER_PORT (log: $SERVER_LOG)"
  nohup "$JDK_HOME/bin/java" -jar "$jar" --server.port="$SERVER_PORT" \
    > "$SERVER_LOG" 2>&1 &
  echo $! > "$SERVER_PID_FILE"
  log "compiler server pid $(cat "$SERVER_PID_FILE")"
}

# ---------------------------------------------------------- healthcheck -----

# Assert the environment really works the way a task needs it to: the built server is
# up and actually compiles and executes Kotlin. Owns all its waiting and keeps polling
# until ready; the launch applies the outer timeout.
healthcheck() {
  local base="http://127.0.0.1:$SERVER_PORT"
  local pid waited=0 body

  pid=$(cat "$SERVER_PID_FILE" 2>/dev/null || true)

  log "healthcheck: waiting for $base/health ..."
  while true; do
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      printf '[startup][error] compiler server (pid %s) exited; last log lines:\n' "$pid" >&2
      tail -40 "$SERVER_LOG" >&2 || true
      return 1
    fi
    if [ "$(curl -s --noproxy '*' --max-time 5 -o /dev/null -w '%{http_code}' "$base/health" || true)" = "200" ]; then
      log "healthcheck: /health is up after ${waited}s"
      break
    fi
    sleep 5
    waited=$((waited + 5))
    if [ $((waited % 30)) -eq 0 ]; then
      log "healthcheck: still waiting for the server (${waited}s elapsed)"
      tail -3 "$SERVER_LOG" 2>/dev/null || true
    fi
  done

  # End-to-end: compile and run a Kotlin program through the REST API. This is what
  # proves the Kotlin compiler, the library folders and the forked executor all work.
  log "healthcheck: compiling and running a Kotlin program via POST /api/compiler/run ..."
  waited=0
  while true; do
    body=$(curl -s --noproxy '*' --max-time 120 \
      -H 'Content-Type: application/json' \
      -d '{"args":"","files":[{"name":"File.kt","text":"fun main() { println(\"air-startup-ok\") }"}]}' \
      "$base/api/compiler/run" || true)

    case "$body" in
      *air-startup-ok*)
        log "healthcheck: server compiled and executed Kotlin successfully"
        return 0
        ;;
    esac

    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      printf '[startup][error] compiler server (pid %s) exited during the run probe; last log lines:\n' "$pid" >&2
      tail -40 "$SERVER_LOG" >&2 || true
      return 1
    fi

    sleep 5
    waited=$((waited + 5))
    log "healthcheck: /api/compiler/run not ready yet (${waited}s elapsed); last response: ${body:0:300}"
  done
}

# ---------------------------------------------------------------- main ------

install_jdk
persist_env
export JAVA_HOME="$JDK_HOME"
export PATH="$JDK_HOME/bin:$PATH"

build_project
prime_docker_images
start_server

if [ -n "$WARMUP" ]; then
  healthcheck || fail "healthcheck failed"
  log "warm-up complete: JDK, Gradle caches and build outputs are ready for the snapshot"
else
  log "server starting in the background; tail $SERVER_LOG to follow it"
fi

log "done"
