server:
  port: ${COMPLETION_SERVICE_PORT:8082}
lsp:
  host: {$LSP_HOST:localhost}
  port: ${LSP_PORT:9999}
  reconnection-retries: 10
  remote-workspace-root: /workspaces/lsp-users-projects-root

springdoc:
  swagger-ui:
    enabled: false