server:
  port: ${COMPLETION_SERVICE_PORT:8082}
lsp:
  host: ${LSP_HOST:localhost}
  port: ${LSP_PORT:9999}
  reconnection-retries: 10
  remote-workspace-root: /workspaces/lsp-users-projects-root
spring:
  docker:
    compose:
      enabled: true
      file: completions/src/main/resources/lsp-compose.yml
      lifecycle-management: start_and_stop
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs/swagger-ui.html