services:
  kotlin-lsp:
    image: sfuri/intellij-lsp
    networks:
      - lsp-lsp-net

  lsp-completions-service:
    image: sfuri/kotlin-compiler-server-completions-lsp
    ports:
      - "${COMPLETIONS_SERVICE_PORT}:8082"
    networks:
      - lsp-lsp-net
    environment:
      - LSP_HOST=kotlin-lsp
      - LSP_PORT=9999
    depends_on:
      - kotlin-lsp

networks:
  lsp-lsp-net:
    driver: bridge
